export const events = [
  {
    id: "event-1",
    title: "Kariyer Günleri 2026",
    category: "Seminer",
    date: "12-10-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Mezunlarla kariyer söyleşileri ve şirket standları.",
    capacity: 120,
  },
  {
    id: "event-2",
    title: "Robotik Atölyesi",
    category: "Atölye",
    date: "15-10-2026",
    time: "10:00",
    location: "Lab 2",
    description: "Arduino ve temel robotik uygulamaları üzerine uygulamalı atölye.",
    capacity: 30,
  },
  {
    id: "event-3",
    title: "Siber Güvenlik Söyleşisi",
    category: "Söyleşi",
    date: "20-10-2026",
    time: "13:30",
    location: "B Blok Konferans Salonu",
    description: "Güncel siber güvenlik tehditleri ve savunma yöntemleri.",
    capacity: 150,
  },
  {
    id: "event-4",
    title: "Yapay Zeka Semineri",
    category: "Seminer",
    date: "22-10-2026",
    time: "15:00",
    location: "Mühendislik Fakültesi Amfisi",
    description: "Yapay zekanın güncel kullanım alanları ve kariyer fırsatları.",
    capacity: 200,
  },
  {
    id: "event-5",
    title: "Web Geliştirme Atölyesi",
    category: "Atölye",
    date: "27-10-2026",
    time: "11:00",
    location: "Bilgisayar Labı",
    description: "HTML, CSS ve JavaScript ile modern web geliştirmeye giriş.",
    capacity: 25,
  },
  {
    id: "event-6",
    title: "Mezunlarla Teknoloji Söyleşisi",
    category: "Söyleşi",
    date: "30-10-2026",
    time: "16:00",
    location: "A Blok Salon",
    description: "Sektörde çalışan mezunlarla teknoloji ve çalışma hayatı üzerine sohbet.",
    capacity: 100,
  },
];
